server:
  port: 9090

spring:
  application:
    name: auth-service

  datasource:
    url: jdbc:mysql://localhost:3306/shopsphere_auth
    username: root
    password: Rushi@12345

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


# =========================
# 🔹 EUREKA CONFIG (FIX)
# =========================
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

  instance:
    hostname: localhost
    prefer-ip-address: false
